"""
植物病害知识库
===============
覆盖 29 类 PlantDoc 数据集中常见作物病害的防治知识，
用于 RAG 检索增强 AI 诊断回答的专业性和准确性。
每条包含：病害名称、英文名、症状描述、化学防治、生物防治、农业措施、传染性、严重程度评级。
"""

KNOWLEDGE_BASE = [
    {
        "name_cn": "苹果疮痂病",
        "name_en": "Apple Scab Leaf",
        "crop": "苹果",
        "symptoms": "叶片出现橄榄绿色至灰褐色圆形病斑，边缘清晰，严重时病斑连片导致叶片卷曲早落。果实表面形成木栓化疮痂状斑点。",
        "chemical": "1. 萌芽前喷施5波美度石硫合剂；2. 花期前后用苯醚甲环唑1500倍液或吡唑醚菌酯2000倍液，间隔7-10天喷1次。",
        "biological": "木霉菌制剂（如哈茨木霉）叶面喷施，每7天1次连续3次，可抑制病原菌孢子萌发。",
        "agricultural": "1. 彻底清除落叶和病果并集中销毁；2. 合理修剪保持树冠通风透光；3. 避免过量氮肥，增施有机肥和磷钾肥。",
        "contagious": True,
        "contagion_note": "可通过风雨传播至周围苹果树，潜伏期约9-17天。孢子可在落叶中越冬。",
        "severity": "中"
    },
    {
        "name_cn": "苹果叶",
        "name_en": "Apple leaf",
        "crop": "苹果",
        "symptoms": "健康苹果叶片，无明显病斑。需与其他病害叶片区分。",
        "chemical": "无需用药。",
        "biological": "无需处理。",
        "agricultural": "保持正常果园管理即可。",
        "contagious": False,
        "contagion_note": "",
        "severity": "无"
    },
    {
        "name_cn": "苹果锈病",
        "name_en": "Apple rust leaf",
        "crop": "苹果",
        "symptoms": "叶片正面出现橙黄色圆形斑点，后期病斑背面长出须状锈孢子器。严重时叶片枯焦早落，果实表面也可受害。",
        "chemical": "1. 花后喷施戊唑醇2000倍液或腈菌唑1500倍液；2. 发病初期用三唑酮1000倍液喷雾，间隔10天1次。",
        "biological": "清除转主寄主（桧柏类植物）是生物防治的关键环节。",
        "agricultural": "1. 果园周围500米内避免种植桧柏等转主寄主；2. 春季降雨前喷施保护性杀菌剂预防；3. 合理灌溉降低果园湿度。",
        "contagious": True,
        "contagion_note": "病原菌需在桧柏上完成越冬，春季产生孢子随风传播至苹果树，传播距离可达数公里。",
        "severity": "中高"
    },
    {
        "name_cn": "甜椒叶",
        "name_en": "Bell_pepper leaf",
        "crop": "甜椒",
        "symptoms": "健康甜椒叶片，无明显病斑。",
        "chemical": "无需用药。",
        "biological": "无需处理。",
        "agricultural": "保持正常管理。",
        "contagious": False,
        "contagion_note": "",
        "severity": "无"
    },
    {
        "name_cn": "甜椒叶斑病",
        "name_en": "Bell_pepper leaf spot",
        "crop": "甜椒",
        "symptoms": "叶片出现圆形或不规则褐色斑点，边缘深褐色，中央灰白色，严重时叶片枯黄脱落。",
        "chemical": "1. 发病初期用代森锰锌600倍液或嘧菌酯1500倍液喷施；2. 每隔7天1次，连续2-3次。",
        "biological": "枯草芽孢杆菌制剂叶面喷施，可有效抑制叶斑病菌。",
        "agricultural": "1. 轮作倒茬，避免连作；2. 合理密植保证通风；3. 采用滴灌减少叶面湿度。",
        "contagious": True,
        "contagion_note": "可通过雨水飞溅和农事操作传播，高温高湿条件下扩散迅速。",
        "severity": "中"
    },
    {
        "name_cn": "蓝莓叶",
        "name_en": "Blueberry leaf",
        "crop": "蓝莓",
        "symptoms": "健康蓝莓叶片，无明显病斑。",
        "chemical": "无需用药。",
        "biological": "无需处理。",
        "agricultural": "保持正常管理，注意土壤pH值维持在4.5-5.5。",
        "contagious": False,
        "contagion_note": "",
        "severity": "无"
    },
    {
        "name_cn": "樱桃叶",
        "name_en": "Cherry leaf",
        "crop": "樱桃",
        "symptoms": "健康樱桃叶片，无明显病斑。",
        "chemical": "无需用药。",
        "biological": "无需处理。",
        "agricultural": "保持正常管理。",
        "contagious": False,
        "contagion_note": "",
        "severity": "无"
    },
    {
        "name_cn": "玉米灰斑病",
        "name_en": "Corn Gray leaf spot",
        "crop": "玉米",
        "symptoms": "叶片出现灰色至灰褐色矩形病斑，受叶脉限制呈条状，后期病斑汇合导致叶片枯死，严重减产。",
        "chemical": "1. 大喇叭口期用苯醚甲环唑+嘧菌酯复配剂喷施；2. 病株率达10%时用吡唑醚菌酯1500倍液喷雾，间隔10天1次。",
        "biological": "选择抗病品种是最有效的生物防治手段。",
        "agricultural": "1. 实行3年以上轮作；2. 收获后彻底清除病残体并深翻土壤；3. 控制氮肥用量，增施钾肥提高抗病性。",
        "contagious": True,
        "contagion_note": "病原菌在病残体上越冬，次年产生分生孢子通过风雨传播，高温高湿季节流行。",
        "severity": "高"
    },
    {
        "name_cn": "玉米叶枯病",
        "name_en": "Corn leaf blight",
        "crop": "玉米",
        "symptoms": "叶片出现水渍状小点，后扩展为长梭形灰褐色大斑，严重时全叶枯死如同火烧状。",
        "chemical": "1. 发病初期用代森锰锌800倍液或多菌灵500倍液喷雾；2. 大斑病严重时可选用嘧菌酯2000倍液。",
        "biological": "利用枯草芽孢杆菌制剂拌种或叶面喷施。",
        "agricultural": "1. 选用抗大斑病品种；2. 合理密植避免田间郁闭；3. 收获后彻底清除田间病残体。",
        "contagious": True,
        "contagion_note": "借风雨传播，温度20-28°C、相对湿度>90%时发病最重，可在田间短距离迅速扩散。",
        "severity": "高"
    },
    {
        "name_cn": "玉米锈病",
        "name_en": "Corn rust leaf",
        "crop": "玉米",
        "symptoms": "叶片散生黄褐色疱状突起（夏孢子堆），破裂后散出锈色粉末，严重时叶片枯黄，光合作用受阻。",
        "chemical": "1. 发病初期用三唑酮1500倍液或戊唑醇2000倍液喷雾；2. 可与代森锰锌混用提高防效。",
        "biological": "暂无成熟生物制剂，以抗病品种为主。",
        "agricultural": "1. 选用抗锈病品种；2. 适期早播避开发病高峰期；3. 合理施肥避免氮肥过量。",
        "contagious": True,
        "contagion_note": "夏孢子通过气流远距离传播，南方玉米区可周年循环侵染，高温多雨条件发病严重。",
        "severity": "中高"
    },
    {
        "name_cn": "桃叶",
        "name_en": "Peach leaf",
        "crop": "桃",
        "symptoms": "健康桃树叶片，无明显病斑。",
        "chemical": "无需用药。",
        "biological": "无需处理。",
        "agricultural": "保持正常管理。",
        "contagious": False,
        "contagion_note": "",
        "severity": "无"
    },
    {
        "name_cn": "马铃薯叶",
        "name_en": "Potato leaf",
        "crop": "马铃薯",
        "symptoms": "健康马铃薯叶片，无明显病斑。",
        "chemical": "无需用药。",
        "biological": "无需处理。",
        "agricultural": "保持正常管理。",
        "contagious": False,
        "contagion_note": "",
        "severity": "无"
    },
    {
        "name_cn": "马铃薯早疫病",
        "name_en": "Potato leaf early blight",
        "crop": "马铃薯",
        "symptoms": "叶片出现暗褐色同心轮纹圆形病斑，周围有黄色晕圈。茎部和块茎也可受害，导致薯块腐烂。",
        "chemical": "1. 发病前用代森锰锌600倍液预防，每隔7-10天1次；2. 发病后用嘧菌酯1500倍液或啶酰菌胺1000倍液喷雾；3. 收获前2周停用。",
        "biological": "枯草芽孢杆菌和木霉菌复配制剂沟施或灌根。",
        "agricultural": "1. 与非茄科作物实行3年以上轮作；2. 收获时避免块茎损伤；3. 贮藏前剔除病薯，保持通风干燥。",
        "contagious": True,
        "contagion_note": "借风雨和灌溉水传播，温暖(24-29°C)潮湿条件下流行，可从伤口侵入块茎。",
        "severity": "中高"
    },
    {
        "name_cn": "马铃薯晚疫病",
        "name_en": "Potato leaf late blight",
        "crop": "马铃薯",
        "symptoms": "叶片边缘或尖端出现水渍状暗绿色斑点，湿度大时叶背出现白色霉层，扩展极快导致全株枯死。块茎变褐腐烂。",
        "chemical": "1. 预防期用代森锰锌或霜脲·锰锌600倍液，每7天1次；2. 发病初期立即用氟啶胺2000倍液或嘧菌酯+烯酰吗啉复配剂喷雾；3. 严重时拔除中心病株并深埋。",
        "biological": "暂无高效生物制剂，以预防为主。",
        "agricultural": "1. 选用抗晚疫病品种；2. 合理灌溉，避免喷灌增加田间湿度；3. 发现中心病株立即连根清除；4. 培土要高，减少块茎感染。",
        "contagious": True,
        "contagion_note": "极强传染性，是历史上爱尔兰大饥荒的元凶。孢子囊通过气流可传播数公里，在凉爽(16-22°C)高湿下48小时即可摧毁整片田块。",
        "severity": "极高"
    },
    {
        "name_cn": "覆盆子叶",
        "name_en": "Raspberry leaf",
        "crop": "覆盆子",
        "symptoms": "健康覆盆子叶片，无明显病斑。",
        "chemical": "无需用药。",
        "biological": "无需处理。",
        "agricultural": "保持正常管理。",
        "contagious": False,
        "contagion_note": "",
        "severity": "无"
    },
    {
        "name_cn": "大豆叶",
        "name_en": "Soyabean leaf",
        "crop": "大豆",
        "symptoms": "健康大豆叶片，无明显病斑。",
        "chemical": "无需用药。",
        "biological": "无需处理。",
        "agricultural": "保持正常管理。",
        "contagious": False,
        "contagion_note": "",
        "severity": "无"
    },
    {
        "name_cn": "南瓜白粉病",
        "name_en": "Squash Powdery mildew leaf",
        "crop": "南瓜/西葫芦",
        "symptoms": "叶片表面出现白色粉状霉层，如同撒了面粉，后期病斑连片覆盖整个叶面，叶片变黄枯死。",
        "chemical": "1. 发病初期喷施三唑酮1500倍液或氟硅唑2000倍液；2. 也可用硫磺悬浮剂400倍液，7天1次连续2-3次；3. 注意白粉病易产生抗药性，应轮换用药。",
        "biological": "枯草芽孢杆菌制剂或碳酸氢钠（小苏打）300倍液叶面喷施效果较好。",
        "agricultural": "1. 选用抗白粉病品种；2. 增施磷钾肥，避免过量氮肥；3. 保证充足光照和通风；4. 及时摘除老叶和病叶。",
        "contagious": True,
        "contagion_note": "借气流传播，分生孢子可远距离扩散。干湿交替条件下发病迅速，干旱季节亦可流行。",
        "severity": "中"
    },
    {
        "name_cn": "草莓叶",
        "name_en": "Strawberry leaf",
        "crop": "草莓",
        "symptoms": "健康草莓叶片，无明显病斑。",
        "chemical": "无需用药。",
        "biological": "无需处理。",
        "agricultural": "保持正常管理。",
        "contagious": False,
        "contagion_note": "",
        "severity": "无"
    },
    {
        "name_cn": "番茄早疫病",
        "name_en": "Tomato Early blight leaf",
        "crop": "番茄",
        "symptoms": "叶片出现暗褐色同心轮纹圆形病斑，周围黄化。茎部和果实也可受害，果面出现暗色凹陷斑。",
        "chemical": "1. 定植后10天开始用代森锰锌600倍液预防；2. 发病后用苯醚甲环唑1500倍液或嘧菌酯2000倍液，间隔7-10天。",
        "biological": "哈茨木霉菌制剂土壤处理和叶面喷施。",
        "agricultural": "1. 与非茄科作物轮作2-3年；2. 采用高畦栽培和滴灌减少湿度；3. 及时摘除下部老叶病叶。",
        "contagious": True,
        "contagion_note": "借风雨和农事操作传播，温暖(24-29°C)多雨季节高发，病残体可在土壤中存活1年以上。",
        "severity": "中高"
    },
    {
        "name_cn": "番茄斑枯病",
        "name_en": "Tomato Septoria leaf spot",
        "crop": "番茄",
        "symptoms": "叶片出现圆形水渍状小斑点，后扩大为灰白色中央有黑色小粒点(分生孢子器)的病斑，叶片由下向上枯死。",
        "chemical": "1. 发病初期用代森锰锌600倍液或苯醚甲环唑2000倍液；2. 可与铜制剂交替使用提高防效。",
        "biological": "枯草芽孢杆菌制剂喷施预防效果较好。",
        "agricultural": "1. 实行2年以上轮作；2. 收获后彻底清除残株落叶并深翻；3. 采用滴灌减少叶面湿润时间。",
        "contagious": True,
        "contagion_note": "借雨水飞溅和昆虫传播，温暖湿润条件(20-25°C)下扩散迅速，以分生孢子器在病残体上越冬。",
        "severity": "中"
    },
    {
        "name_cn": "番茄叶",
        "name_en": "Tomato leaf",
        "crop": "番茄",
        "symptoms": "健康番茄叶片，无明显病斑。",
        "chemical": "无需用药。",
        "biological": "无需处理。",
        "agricultural": "保持正常管理。",
        "contagious": False,
        "contagion_note": "",
        "severity": "无"
    },
    {
        "name_cn": "番茄细菌性斑点病",
        "name_en": "Tomato leaf bacterial spot",
        "crop": "番茄",
        "symptoms": "叶片出现暗褐色水渍状小斑点，周围有黄色晕圈，后期斑点连片导致叶片枯焦。果实表面也可形成凸起斑点。",
        "chemical": "1. 发病初期用氢氧化铜（可杀得）500倍液或春雷霉素1000倍液喷雾；2. 铜制剂应避免在高温时使用以防药害。",
        "biological": "抗生素类生物农药如中生菌素、多抗霉素。",
        "agricultural": "1. 选用无病种子，种子用52°C热水处理30分钟；2. 避免在叶片潮湿时进行农事操作；3. 增施磷钾肥提高抗病力。",
        "contagious": True,
        "contagion_note": "通过雨水、灌溉水、昆虫传播，高温高湿环境暴发迅速，病原菌可在种子和病残体中存活。",
        "severity": "中"
    },
    {
        "name_cn": "番茄晚疫病",
        "name_en": "Tomato leaf late blight",
        "crop": "番茄",
        "symptoms": "叶片边缘或尖端出现暗绿色水渍状大斑，湿度高时叶背长出白色霉层。茎部出现黑褐色条斑，果实变褐腐烂。病程极快，3-5天可摧毁整棚。",
        "chemical": "1. 预防期定期喷施代森锰锌或霜脲·锰锌500倍液，每5-7天1次；2. 发现病株立即用氟啶胺2000倍液或嘧菌酯+烯酰吗啉复配剂全田喷雾；3. 严重发病田块可选用氟噻唑吡乙酮（增威赢绿）2000倍液特效治疗。",
        "biological": "暂无高效生物药剂，以化学预防为主。",
        "agricultural": "1. 选择抗病品种；2. 合理密植、加强通风；3. 采用膜下滴灌降低棚内湿度至70%以下；4. 发现中心病株立即拔除深埋，周围喷药封锁。",
        "contagious": True,
        "contagion_note": "极高传染性，是番茄生产中最具毁灭性的病害。孢子囊通过气流可传播数十公里。在凉爽(18-22°C)高湿(>90%)条件下24-48小时即可完成侵染，整棚番茄可在数日内全部毁灭。",
        "severity": "极高"
    },
    {
        "name_cn": "番茄花叶病毒病",
        "name_en": "Tomato leaf mosaic virus",
        "crop": "番茄",
        "symptoms": "叶片出现深浅绿相间的花叶斑驳，叶片皱缩变形，植株矮化。果实可能出现褐色坏死条纹或斑块。",
        "chemical": "病毒病无特效化学药剂，主要以预防和病毒抑制剂缓解为主：1. 发病初期用20%吗胍·乙酸铜粉剂500倍液或氨基寡糖素800倍液喷雾，每5-7天1次；2. 配合叶面肥（磷酸二氢钾）喷施增强植株抗性。",
        "biological": "利用弱毒株系交叉保护接种。",
        "agricultural": "1. 选用抗TMV品种；2. 种子用10%磷酸三钠浸泡20分钟消毒；3. 操作前用肥皂水洗手或用脱脂牛奶浸泡工具；4. 彻底防治蚜虫（主要传毒媒介）；5. 发现病株及时拔除。",
        "contagious": True,
        "contagion_note": "主要通过汁液接触传播（农事操作、整枝打杈），也可经蚜虫传毒。在土壤和病残体中可存活1年以上。极微量的病株汁液即可传染健康植株。",
        "severity": "高"
    },
    {
        "name_cn": "番茄黄化曲叶病毒病",
        "name_en": "Tomato leaf yellow virus",
        "crop": "番茄",
        "symptoms": "叶片向上卷曲、变小、黄化，植株明显矮缩，生长停滞。花器发育不良导致落花落果，严重影响产量。",
        "chemical": "1. 重点防治传毒媒介——烟粉虱：用吡虫啉1000倍液或啶虫脒1500倍液喷雾；2. 发病初期喷施氨基寡糖素或菇类蛋白多糖提高抗性。",
        "biological": "释放丽蚜小蜂等天敌控制烟粉虱种群。",
        "agricultural": "1. 选用抗TYLCV品种（最关键措施）；2. 苗床用40-60目防虫网覆盖；3. 彻底清除田间杂草和病株；4. 避免在烟粉虱活动高峰（清晨和傍晚）进行农事操作。",
        "contagious": True,
        "contagion_note": "仅由烟粉虱（B型/Q型）持久性传毒，不能通过汁液接触传播。烟粉虱获毒后可终生传毒。南方地区周年可流行。",
        "severity": "极高"
    },
    {
        "name_cn": "番茄叶霉病",
        "name_en": "Tomato mold leaf",
        "crop": "番茄",
        "symptoms": "叶片正面出现黄绿色褪绿斑，叶背对应处出现灰紫色至棕褐色绒状霉层，严重时叶片自下而上枯死。",
        "chemical": "1. 发病初期用嘧菌酯1500倍液或氟硅唑2000倍液喷雾；2. 也可选用多菌灵+代森锰锌复配剂，7天1次连续2-3次。",
        "biological": "枯草芽孢杆菌制剂叶背重点喷施。",
        "agricultural": "1. 选用抗叶霉病品种；2. 加强通风排湿，棚内湿度控制在80%以下；3. 合理密植避免田间郁闭；4. 及时摘除病叶老叶并集中深埋。",
        "contagious": True,
        "contagion_note": "借气流传播，分生孢子可在温室和塑料大棚内周年循环侵染。高湿(>85%)是本病的决定性因素。",
        "severity": "中高"
    },
    {
        "name_cn": "番茄二斑叶螨为害",
        "name_en": "Tomato two spotted spider mites leaf",
        "crop": "番茄",
        "symptoms": "叶片出现细密黄色斑点，似砂纸状，严重时整叶变黄、干枯。叶背可见极小的红色成虫和白色卵粒，结有细丝网。",
        "chemical": "1. 用阿维菌素1500倍液或联苯肼酯2000倍液喷雾，重点喷施叶背；2. 螨类易产生抗药性，应轮换使用不同杀螨剂如哒螨灵、螺螨酯等。",
        "biological": "释放捕食螨（如智利小植绥螨、胡瓜钝绥螨）效果显著，每亩释放10-20万头。",
        "agricultural": "1. 保持田间湿度在60%以上（螨类喜干燥）；2. 清除田边杂草减少虫源；3. 避免高温干旱季节大水漫灌。",
        "contagious": True,
        "contagion_note": "可通过爬行、吐丝下垂借风传播、农事操作等途径扩散。高温(>30°C)干燥条件下繁殖极快，世代重叠，7-10天可完成一代。",
        "severity": "中"
    },
    {
        "name_cn": "葡萄叶",
        "name_en": "grape leaf",
        "crop": "葡萄",
        "symptoms": "健康葡萄叶片，无明显病斑。",
        "chemical": "无需用药。",
        "biological": "无需处理。",
        "agricultural": "保持正常管理。",
        "contagious": False,
        "contagion_note": "",
        "severity": "无"
    },
    {
        "name_cn": "葡萄黑腐病",
        "name_en": "grape leaf black rot",
        "crop": "葡萄",
        "symptoms": "叶片出现红褐色圆形斑点，后期中央变灰白色边缘黑褐色。果实受害后变褐、干缩成黑色僵果挂在枝上不脱落。",
        "chemical": "1. 花前用代森锰锌600倍液预防；2. 花后和幼果期用嘧菌酯2000倍液或甲基硫菌灵1000倍液，间隔10-14天1次。",
        "biological": "木霉菌制剂开花前预防性喷施。",
        "agricultural": "1. 清除并销毁园内僵果、病枝和病叶；2. 冬季修剪后彻底清园并喷施石硫合剂；3. 合理修剪保持架面通风透光。",
        "contagious": True,
        "contagion_note": "借雨水飞溅传播，温暖(22-27°C)多雨天气最易侵染。病原菌在僵果和病枝中越冬。",
        "severity": "中高"
    },
]
